# Site settings
title: Team 56K
email: eli.m.goodman@gmail.com
description: This is our site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  team56k

# Build settings
markdown: kramdown
